language: node_js
node_js:
- stable
sudo: false
notifications:
  slack:
    secure: F18NdR2i/+xvayi8pFX2I3FdB8UyEnbRPMHtT+qsjKc5aionSeqYfpxeHEKFdIbdfd6W1LwzfElEy4OdfLsiaAIendlv/9o5lqiJuzAc/iAs/KAIyxpE/0+2SoVA3rXdgZ3h8T3hHf9DijpYAMLJVZwXEzdGrhlZkSGMwY08C2ZCvrRebwNo9D3CdOv1rEDJl0c1KBaS4mZqxY2GcS3Qg6erc18fJ4n+C2phH4qu9CqiqI7BRCRqGUqcU11U8+u8xjGvl1A7SpqNUj6GS8VTbOzPlux3MdD+ZJKreVGBh5L58DNnS21AqFyv7u9Zwo/Bg6EAipfBe0hJeGIhmc9pZm/UZaLGO8c6zSPY3iL/JW37LAYzsV+B6wCtgGJNDn0iZd5F8bnWC/8U25Cpb3i05AVYy0ThOvI7yPhFuv40OzALeiFDQLb/ptCSKDAOKyJFgFsgwQUbgDrZnMPw9+eV8ZXsnjL7muGUlq4lmA6DLhlsxw74thM9+h7PO0BRaR1IvMvQeV3TZVHhpLYGnpJZVkAO+zvWo1tQIBhqIFP+DdylvL7ixpydrpERZnq3qLdYhdXi2qahQ1kIzuSrE/1l6Iw4ETw6HmX9KNNhCA2A8OgR9OHTZybmn1u+EyLZ1a3YspELaYaQniGd8M4nwipERiXb3VzZFZwelKEn+4uqkjc=
